### ISSUE TITLE
Add IDEAFuse Registration Date

### ISSUE THREAD

**Issue by wisn** [helloproclub/scpc-archive#4]
I think the registration date almost the same with ITobaFest. Need to wait until the website up.

**Comment by pamungkaski** [comment]
The Ideafuse website already Up, https://ideafuse.mikroskil.ac.id/2018/acm-icpc
Itboafest http://itobafest.del.ac.id

**Comment by pamungkaski** [comment]
Sry, the itobafest has not been updated

**Comment by wisn** [comment]
Ooops! Forgot to add the `List of SCPC` section.
